// Generated by view binder compiler. Do not edit!
package win.arbitrarilytong.settings.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.CollapsingToolbarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import win.arbitrarilytong.settings.R;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final MaterialToolbar appBar;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final CollapsingToolbarLayout collapsingToolbarLayout;

  @NonNull
  public final TextView headerBuildDate;

  @NonNull
  public final TextView headerBuildVersion;

  @NonNull
  public final TextView headerLastCheck;

  @NonNull
  public final TextView headerTitle;

  @NonNull
  public final ImageView romLogo;

  private ActivityMainBinding(@NonNull CoordinatorLayout rootView, @NonNull MaterialToolbar appBar,
      @NonNull AppBarLayout appBarLayout, @NonNull CollapsingToolbarLayout collapsingToolbarLayout,
      @NonNull TextView headerBuildDate, @NonNull TextView headerBuildVersion,
      @NonNull TextView headerLastCheck, @NonNull TextView headerTitle,
      @NonNull ImageView romLogo) {
    this.rootView = rootView;
    this.appBar = appBar;
    this.appBarLayout = appBarLayout;
    this.collapsingToolbarLayout = collapsingToolbarLayout;
    this.headerBuildDate = headerBuildDate;
    this.headerBuildVersion = headerBuildVersion;
    this.headerLastCheck = headerLastCheck;
    this.headerTitle = headerTitle;
    this.romLogo = romLogo;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.app_bar;
      MaterialToolbar appBar = ViewBindings.findChildViewById(rootView, id);
      if (appBar == null) {
        break missingId;
      }

      id = R.id.app_bar_layout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.collapsing_toolbar_layout;
      CollapsingToolbarLayout collapsingToolbarLayout = ViewBindings.findChildViewById(rootView, id);
      if (collapsingToolbarLayout == null) {
        break missingId;
      }

      id = R.id.header_build_date;
      TextView headerBuildDate = ViewBindings.findChildViewById(rootView, id);
      if (headerBuildDate == null) {
        break missingId;
      }

      id = R.id.header_build_version;
      TextView headerBuildVersion = ViewBindings.findChildViewById(rootView, id);
      if (headerBuildVersion == null) {
        break missingId;
      }

      id = R.id.header_last_check;
      TextView headerLastCheck = ViewBindings.findChildViewById(rootView, id);
      if (headerLastCheck == null) {
        break missingId;
      }

      id = R.id.header_title;
      TextView headerTitle = ViewBindings.findChildViewById(rootView, id);
      if (headerTitle == null) {
        break missingId;
      }

      id = R.id.rom_logo;
      ImageView romLogo = ViewBindings.findChildViewById(rootView, id);
      if (romLogo == null) {
        break missingId;
      }

      return new ActivityMainBinding((CoordinatorLayout) rootView, appBar, appBarLayout,
          collapsingToolbarLayout, headerBuildDate, headerBuildVersion, headerLastCheck,
          headerTitle, romLogo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
